services:
  # --------------------
  # Jenkins
  # --------------------
  jenkins:
    image: devops-jenkins:latest
    container_name: devops-jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - ./jenkins/plugins.txt:/usr/share/jenkins/ref/plugins.txt
      - ./jenkins/casc:/var/jenkins_home/casc_configs
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=false

  # --------------------
  # Local Docker Registry
  # --------------------
  registry:
    image: registry:2
    container_name: devops-registry
    ports:
      - "5000:5000"
    volumes:
      - registry_data:/var/lib/registry
      - ./registry/auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: "Registry Realm"
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd

  # --------------------
  # Prometheus
  # --------------------
  prometheus:
    image: prom/prometheus:latest
    container_name: devops-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./observability/prometheus.yml:/etc/prometheus/prometheus.yml:ro

volumes:
  jenkins_home:
  registry_data:
